name: catcher
description: Error catching plugin
version: 0.0.1
author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/catcher

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^2.2.11
  device_info: ^0.4.0
  package_info: ^0.4.0
  mailer: ^2.2.0
  dio: ^1.0.14
  flutter_local_notifications: ^0.4.4+2
flutter:
  plugin:
    androidPackage: com.jhomlala.catcher
    pluginClass: CatcherPlugin

